# Docs: https://docs.codeclimate.com/docs/advanced-configuration
version: '2'
exclude_patterns:
  - '**/coverage/'
  - '**/docs/'
  - '**/dist/'
  - '**/node_modules/'
  - '**/scripts/'
  - '**/__tests__/'
  - '**/*.d.ts'
